"""Initial migraton

Revision ID: 86460131dd73
Revises: ac0170ec2251
Create Date: 2024-01-12 17:30:20.153956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86460131dd73'
down_revision = 'ac0170ec2251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.String(length=15), nullable=False))
        batch_op.create_unique_constraint(None, ['ID'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=15), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###
