"""add body_kr col for BlogPost

Revision ID: d5e52471f139
Revises: 9798d5fc2843
Create Date: 2024-03-08 17:25:35.477616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e52471f139'
down_revision = '9798d5fc2843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_kor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('body_kor')

    # ### end Alembic commands ###
